#ifndef VCK5000_REGS_H_
#define VCK5000_REGS_H_

#define VERSION REG		0
#define NUM_QUEUES_REG		4
#define QUEUE_DESC_OFFSET_REG	16
#define QUEUE_DESC_SIZE_REG	20
#define QUEUE_BUF_OFFSET_REG	24
#define QUEUE_BUF_SIZE_REG	28
#define SIGNAL_OFFSET_REG	32
#define SIGNAL_SIZE_REG		36
#define DOORBELL_OFFSET_REG	40
#define DOORBELL_SIZE_REG	44

#endif /*  VCK5000_REGS_H_ */
